{% set name = "xrft" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/rabernat/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: "3172ef612134dc28f228852c4b95ddbc2437bdafcae64b2ab53311c29c9b1606"
  
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - xarray

test:
  imports:
    - xrft
    - xrft.tests

about:
  home: https://github.com/rabernat/xrft
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fourier transforms for xarray data'
  dev_url: https://github.com/rabernat/xrft

extra:
  recipe-maintainers:
    - kynan
    - rabernat
